version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_PASSWORD}
      POSTGRES_PASSWORD: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '12432:5432'

  redis:
    image: redis
    ports:
      - '4379:6379'
volumes:
  db_data:
